### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by tedwoodward** [christopheml/soulshape-journal#1]
I downloaded the latest version as a zip, and it unzipped to soulshape-journal-master. I dropped that into my Addons directory, but WoW didn't see it.

I changed the name of the directory to SoulshapeJournal (to match the .toc), and WoW could see it.

Please mention this in the readme. Better yet, put it up on CurseForge.

Thanks for making this!

**Comment by christopheml** [comment]
Hello, thanks for your feedback.
I'll add a section for manual installation from Github and I'm planning on releasing it on Curseforge in a couple of days.

Considering the issue you had, I think you downloaded the source archive and not the fully packaged one.
This is the direct link to the latest version, you should be able to unzip it directly in your Addons folder like any other one : https://github.com/christopheml/soulshape-journal/releases/download/0.5/SoulshapeJournal-0.5.zip

**Comment by christopheml** [comment]
[Readme](https://github.com/christopheml/soulshape-journal/blob/master/README.md) should now have installation instructions. Feel free to reopen if you encounter any issue.

**Comment by tedwoodward** [comment]
Thank you!
