### ISSUE TITLE
Minor source info update & textbox search

### ISSUE THREAD

**Issue by WuSage3** [christopheml/soulshape-journal#10]
1) Goat Soul comes from more than just Ardenweald callings according to some comments here https://www.wowhead.com/item=187880/goat-soul
2) Shoveltusk Soul comes from just about any PvP Brawl according to some comments here https://www.wowhead.com/item=185048/shoveltusk-soul
3) Make search box case-insensitive to match Blizzard's search boxes on the other tabs

**Comment by christopheml** [comment]
Hello, I'm on a trip abroad and I'll pick up these modifications asap.
Thanks for the reporting.

**Comment by WuSage3** [comment]
Thank you! You're awesome

**Comment by christopheml** [comment]
Seems to be the case for Snake Soul also.
