### ISSUE TITLE
Incomplete source for Bunny Soul

### ISSUE THREAD

**Issue by meandmykeks** [christopheml/soulshape-journal#15]
Bunny Soul can be the reward from _**any**_ of the Shadowlands pet battle world quests, not just in Ardenweald. Got mine in Maldraxxus. Ther're confirming comments for all four regions in Shadowlands on wowhead: [https://www.wowhead.com/item=187858/bunny-soul#comments](https://www.wowhead.com/item=187858/bunny-soul#comments)

**Comment by christopheml** [comment]
Hello, thanks for bringing this information up.
I'm currently abroad and cannot fix this right now, but I'll pick that up asap when I'm back.
