### ISSUE TITLE
Localization "Soulshape Journal" title

### ISSUE THREAD

**Issue by meandmykeks** [christopheml/soulshape-journal#17]
Can you please localize the "Soulshape Journal" title?

**Comment by christopheml** [comment]
Hello, I wasn't sure I really needed to translate it as it's verbatim the name of the addon, but that might not be great for russian users or (upcoming chinese users). I'll try to see whan the consensus is for popular addon and will update accordingly.

**Comment by christopheml** [comment]
It's been added as a translation key, although it's pretty much optional. I'll leave it to translator's preference for their own locales.
