### ISSUE TITLE
Issue with BetterWardrobe

### ISSUE THREAD

**Issue by Morraine** [christopheml/soulshape-journal#19]
Hi,
 first I like this addon, but it dont work with BetterWardrobe.  There is no error message, it prevents the loading of this addonfeatures like Extra, Saved,  Sort and so on

**Comment by christopheml** [comment]
Hello, I'm on a trip abroad and will be investingating issues asap.
Thanks for the reporting.

AFAIK, addons use different ways of adding a new tab to the collection journal that may not be compatible, I'll see if I can find something that works properly.
