### ISSUE TITLE
Shadowstalker Soul entry displays wrong model

### ISSUE THREAD

**Issue by penguinsane** [christopheml/soulshape-journal#26]
Shadowstalker Soul in the journal displays a warpstalker model instead of the cat model it should be (I don't even think there is a warpstalker soul lol)

![Wow_BWKe8olkIf](https://user-images.githubusercontent.com/6591625/150646914-80800260-2352-4516-936f-62e93398d039.png)

**Comment by christopheml** [comment]
Oh, good catch, seems I'm going to go 3D model fishing again 😬
