### ISSUE TITLE
Lua Error with the Latest version 0.9

### ISSUE THREAD

**Issue by Galthariel** [christopheml/soulshape-journal#29]
1x SoulshapeJournal\Localization\koKR-Korean.lua:29: attempt to index local 'L' (a nil value)
[string "@SoulshapeJournal\Localization\koKR-Korean.lua"]:29: in main chunk

Locals:
ADDON = "SoulshapeJournal"
_ = <table> {
}
L = nil
(*temporary) = <table> {
 apps = <table> {
 }
 GetLocale = <function> defined @Ace3\AceLocale-3.0\AceLocale-3.0.lua:132
 NewLocale = <function> defined @Ace3\AceLocale-3.0\AceLocale-3.0.lua:93
 appnames = <table> {
 }
}
(*temporary) = "SoulshapeJournal"
(*temporary) = "koKR"
(*temporary) = false
(*temporary) = "attempt to index local 'L' (a nil value)"

**Comment by christopheml** [comment]
Thanks for your report, I'm not it, should be fixed in the next hour.

**Comment by christopheml** [comment]
0.9.1 is up here and on Curseforge, this should fix the issue.
