### ISSUE TITLE
Wyvern soul also available from brawls

### ISSUE THREAD

**Issue by WuSage3** [christopheml/soulshape-journal#36]
Hi,

I got Wyvern Soul today from the comp stomp PvP brawl.

**Comment by christopheml** [comment]
Hello, I've cross-checked with Wowhead and it seems that the Wyvern Soul indeed drops from Comp Stomp.
As Gryphon Soul up to now usually dropped from the same modes, I'll update both to add the Comp Stomp Brawl as sources.

**Comment by WuSage3** [comment]
I am not sure if it comes from other brawls or not, and haven't gotten Gryphon Soul from comp stomp yet - so I just didn't want to speak for anything I didn't experience or find out for myself.

Either way, thanks!
