### ISSUE TITLE
Add filtering to ease navigation.

### ISSUE THREAD

**Issue by christopheml** [christopheml/soulshape-journal#4]
Filters : 
- Collected/Not collected
- Drop/Quest/Vendor
- ?

**Comment by tarnin** [comment]
Sure.  How about, at the very least, separated by Crittershape and Soulshape.

**Comment by christopheml** [comment]
Yes, good catch. I've been a little busy recently and couldn't quite progress on the addon, but I'll be on it soon.
In the meantime, crittershapes in the list have a background with a mouse icon (but that's not as practical as a filter)

**Comment by tarnin** [comment]
> Yes, good catch. I've been a little busy recently and couldn't quite progress on the addon, but I'll be on it soon. In the meantime, crittershapes in the list have a background with a mouse icon (but that's not as practical as a filter)

Ohhh that's slick!

**Comment by christopheml** [comment]
Closing this issue as it's too broad to track changed properly.
