### ISSUE TITLE
Getting following lua error at startup (version 0.5)

### ISSUE THREAD

**Issue by rousseauxy** [christopheml/soulshape-journal#5]
Message: ...erface\AddOns\SoulshapeJournal\Localization\frFR.lua:29: attempt to index local 'L' (a nil value)
Time: Thu Nov 25 23:54:17 2021
Count: 1
Stack: ...erface\AddOns\SoulshapeJournal\Localization\frFR.lua:29: attempt to index local 'L' (a nil value)
[string "@Interface\AddOns\SoulshapeJournal\Localization\frFR.lua"]:29: in main chunk

Locals: ADDON = "SoulshapeJournal"
_ = <table> {
}
L = nil
(*temporary) = <table> {
 apps = <table> {
 }
 GetLocale = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0.lua:132
 NewLocale = <function> defined @Interface\AddOns\AddOnSkins\Libs\Ace3\AceLocale-3.0\AceLocale-3.0.lua:93
 appnames = <table> {
 }
}
(*temporary) = "SoulshapeJournal"
(*temporary) = "frFR"
(*temporary) = false
(*temporary) = "attempt to index local 'L' (a nil value)"

**Comment by christopheml** [comment]
Hello and thanks for your report.

This bug should be fixed in [release 0.6](https://github.com/christopheml/soulshape-journal/releases/tag/0.6). Please let me know.
