### ISSUE TITLE
Missing 9.2 Souls found

### ISSUE THREAD

**Issue by meandmykeks** [christopheml/soulshape-journal#51]
According to wowhead:

- the **Cervid Soul** drops from Prototype Pantheon (Sepulcher of the First Ones).
https://www.wowhead.com/item=190337/cervid-soul

- the **Gromit Soul** has a chance to drop from Shrouded Cypher Cache in Zereth Mortis.
https://www.wowhead.com/item=189983/gromit-soul

- the **Ray Soul** can drop from Enlightened Broker Supplies, the paragon reward from The Enlightened.
https://www.wowhead.com/item=189973/ray-soul

- the **Silithid Soul** drops from The Jailer (Sepulcher of the First Ones).
https://www.wowhead.com/item=189982/silithid-soul

- the **Snail Soul** drops from High Value Cache inside Sepulcher of the First Ones.
https://www.wowhead.com/item=189991/snail-soul

**Comment by christopheml** [comment]
Thank you for summarizing all of those, will update asap.
