### ISSUE TITLE
support non curseforge clients

### ISSUE THREAD

**Issue by JPEscher** [christopheml/soulshape-journal#60]
Hi Team, any plans to integrate with a non curseforge provider?

https://www.wowhead.com/news/ads-revenue-and-api-wowup-and-overwolf-split-over-addon-development-325912
https://www.patreon.com/posts/curseforge-62354064
https://wowup.io/guide/wowup/curseforge-migration

**Comment by christopheml** [comment]
Hello, as the addon is hosted on github, it should already work without CurseForge. I'll test with WowUp and get back to you.

**Comment by christopheml** [comment]
I can confirm Soulshape Journal can already be installed from Github in the WowUp client (no need for Curseforge), I updated the readme to reflect this.
