### ISSUE TITLE
toc update ?

### ISSUE THREAD

**Issue by tatatada** [christopheml/soulshape-journal#62]
will u update toc for pre-patch or for dragonflight ?

**Comment by christopheml** [comment]
Hello, I'll update the toc when the addon is compatible with 10.0, which is not the case at the moment. I'm a little short on time but you have a temporary fix in this thread : https://github.com/christopheml/soulshape-journal/issues/61

**Comment by tatatada** [comment]
thx for confirming you will update it. loving ur addon. thank you very much
