### ISSUE TITLE
Journal doesn't appear with collection tab

### ISSUE THREAD

**Issue by valkyriestealth** [christopheml/soulshape-journal#63]
I've tried reloading the UI, closing the game, restarting my pc and nothing will make the soulshape journal appear. It shows up in the addon list but nowhere else. Please help.

**Comment by christopheml** [comment]
Hello, the addon is currently not working with patch 10.0.

Resourceful users have provided a temporary fix in this thread : https://github.com/christopheml/soulshape-journal/issues/61
