### ISSUE TITLE
loaded this addon and immediately got errors

### ISSUE THREAD

**Issue by linda535** [christopheml/soulshape-journal#64]
Message: bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
Time: Sun Nov 13 10:48:39 2022
Count: 1
Stack: bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
[string "=[C]"]: in function `CreateTexture'
[string "@Interface/AddOns/SoulshapeJournal/UI/SoulshapeJournal.lua"]:185: in function <...face/AddOns/SoulshapeJournal/UI/SoulshapeJournal.lua:166>
[string "@Interface/AddOns/SoulshapeJournal/UI/SoulshapeJournal.lua"]:386: in function `CreateCollectionPanel'
[string "@Interface/AddOns/SoulshapeJournal/Core.lua"]:46: in function <Interface/AddOns/SoulshapeJournal/Core.lua:38>
[string "=[C]"]: ?
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <.../AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

**Comment by christopheml** [comment]
I'm still working on 10.0 compatibility, people have figured out a temporary fix in this thread : https://github.com/christopheml/soulshape-journal/issues/61
