### ISSUE TITLE
Addon out of date

### ISSUE THREAD

**Issue by ZaneBusby** [christopheml/soulshape-journal#67]
Not sure if the addon just needs a ToC update, or something larger, but addon no longer works since Dragonflight pre-patch.

**Comment by christopheml** [comment]
It's just a matter of TOC update, the addon works in Dragronflight pre-patch but will show as 'outdated'. I'll bump it soon.

**Comment by christopheml** [comment]
Fixed in 1.2.3. It's available on GitHub right now and should be available on CurseForge very soon.
