### ISSUE TITLE
Tracking quest IDs for Cat Soul (Well Fed) and Corgi Soul

### ISSUE THREAD

**Issue by Dairyman** [christopheml/soulshape-journal#7]
Cat Soul (Well Fed): `64982`
Corgi Soul: `64939`

**Comment by christopheml** [comment]
I've ran `/run print(C_QuestLog.IsQuestFlaggedCompleted(64939))` on a character that unlocked the Corgi Soul and it returned `false`. Even if the quest is meant to track that soul I can't reliably use it.

**Comment by madcowfred** [comment]
As an update, I just did it on a Horde character with quest debugging and got this:

```
[11:57:20] You pet Sparkle.
[11:57:22] Sparkle barks excitedly at you!
[11:57:22] DEBUG: Quest 64938 changed: false => true
```

And on an Alliance character:

```
[12:00:24] You pet Sparkle.
[12:00:25] Sparkle barks excitedly at you!
[12:00:26] DEBUG: Quest 64938 changed: false => true
```

**Comment by madcowfred** [comment]
And just to confirm Ma'oh's one:

```
[12:57:37] You receive loot: [Spectral Feed]
[12:58:39] You meow at Ma'oh.
[12:58:40] Ma'oh meows at you hungrily.
[12:58:44] Ma'oh meows loudly, enjoying the meal.
[12:58:44] DEBUG: Quest 64982 changed: false => true
```

**Comment by christopheml** [comment]
@madcowfred Thanks for the detailed info.  Out of curiosity, how did you get that debug output for quests?

**Comment by madcowfred** [comment]
> @madcowfred Thanks for the detailed info. Out of curiosity, how did you get that debug output for quests?

I've been using the HandyNotes Shadowlands developer mode for it, I believe ALL THE THINGS also has a debug mode that does something similar - https://github.com/zarillion/handynotes-plugins/blob/master/core/dev.lua explains how to enable. It's basically just a timer that queries every single quest you've completed every 1-2 seconds and tells you when anything changes, but it's been _highly_ useful!
