### ISSUE TITLE
Not working anymore with 11.0 and 11.0.2

### ISSUE THREAD

**Issue by Flanell88** [christopheml/soulshape-journal#71]
Sadly the Addon doesnt show up anymore with TWW prepatch 11.0. Is there a way to fix it?

**Comment by Agramon** [comment]
I think I fixed it by replacing the following line in SoulshapeDatabase.lua (line 102):
- name, _ = GetFactionInfoByID(faction.id)
with
name = C_Reputation.GetFactionDataByID(faction.id).name

This is due to Faction API changes in 11.0

**Comment by zalidthebur** [comment]
That fixed it :-)

**Comment by ChesterYue** [comment]
> I think I fixed it by replacing the following line in SoulshapeDatabase.lua (line 102):
> 
> * name, _ = GetFactionInfoByID(faction.id)
>   with
>   name = C_Reputation.GetFactionDataByID(faction.id).name
> 
> This is due to Faction API changes in 11.0

nice. maybe you can open a PR.

**Comment by Flanell88** [comment]
And its broken again with 11.0.2 -.-

Any ideas how to fix it?

**Comment by tailcat** [comment]
> And its broken again with 11.0.2 -.-
> 
> Any ideas how to fix it?

In SoulshapeJournal/UI/SoulshapeJournal.lua change GetSpellTexture to C_Spell.GetSpellTexture (line 88 and 377)

I have created a pull request https://github.com/christopheml/soulshape-journal/pull/72

**Comment by martinboy1974** [comment]
Still not working. After making the suggested by Agramon and tailcat, I still this:

1x SoulshapeJournal/Core.lua:43: attempt to call global 'LoadAddOn' (a nil value)
[string "@SoulshapeJournal/Core.lua"]:43: in function <SoulshapeJournal/Core.lua:38>
[string "=[C]"]: ?
[string "@BagSync/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ceBagSync/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@BagSync/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@BagSync/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ceBagSync/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
self = <table> {
 BUILD_9_2 = 42069
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 FrameLevelType = "PIN_FRAME_LEVEL_SOULSHAPE_JOURNAL"
 name = "SoulshapeJournal"
 saved = <table> {
 }
 orderedModules = <table> {
 }
 BUILD_9_1_5 = 40871
 BUILD_9_0_5 = 37862
 Database = <table> {
 }
 baseName = "SoulshapeJournal"
 Filters = <table> {
 }
 BUILD_9_0 = 37474
 enabledState = true
 defaultModuleState = true
 BUILD_9_1 = 39185
 UIFactory = <table> {
 }
}
(*temporary) = nil
(*temporary) = "Blizzard_Collections"
(*temporary) = "attempt to call global 'LoadAddOn' (a nil value)"

**Comment by tailcat** [comment]
line 43 change LoadAddon to C_AddOns.LoadAddOn

FYI https://warcraft.wiki.gg/wiki/Patch_11.0.2/API_changes is what I used to figure these things out

**Comment by martinboy1974** [comment]
> line 43 change LoadAddon to C_AddOns.LoadAddOn
> 
> FYI https://warcraft.wiki.gg/wiki/Patch_11.0.2/API_changes is what I used to figure these things out

Thanks, that worked. Took your advice and edited the lua errors in the addon PetBattleMaster too and I now got rid of the lua errors there too.

**Comment by halloaloe** [comment]
@tailcat Thank you so much for your work here! I'm glad there's people that help keep addons going if the author is unreachable/unresponsive. As I don't know how to message you otherwise, I'm asking here. Would you take a look please at https://legacy.curseforge.com/wow/addons/cloudy-pet-collected and https://legacy.curseforge.com/wow/addons/work_complete as they are little addons that haven't been maintained in ages, but are so very helpful, I'd like for them to keep going.

**Comment by tailcat** [comment]
> On Aug 18, 2024, at 6:18 AM, halloaloe ***@***.***> wrote:
> 
> 
> @tailcat Thank you so much for your work here! I'm glad there's people that help keep addons going if the author is unreachable/unresponsive. As I don't know how to message you otherwise, I'm asking here. Would you take a look please at https://legacy.curseforge.com/wow/addons/cloudy-pet-collected and https://legacy.curseforge.com/wow/addons/work_complete as they are little addons that haven't 

Fixing CloudyPetCollected has me stumped, but attached is my fix for Work_Complete

diff -rc Work_Complete/Work_Complete.lua /Applications/Games/World of Warcraft/_retail_/Interface/AddOns/Work_Complete/Work_Complete.lua
*** Work_Complete/Work_Complete.lua	Sun Aug 18 12:06:35 2024
--- /Applications/Games/World of Warcraft/_retail_/Interface/AddOns/Work_Complete/Work_Complete.lua	Sun Aug 18 12:30:26 2024
***************
*** 810,816 ****
  -- events for all addons loaded later).--
  -- this function works once when this addon loads
  	if arg1_name == "Work_Complete" then
! 		DEFAULT_CHAT_FRAME:AddMessage(myRed.."---["..myWhite.."Work_Complete"..myRed.."]---"..myYellow.." ver:"..myGreen..GetAddOnMetadata("Work_Complete", "Version")..myWhite.." by "..myBlue.."PunksNotDead");
  		-- check if this is the first time the variables have been loaded
  		if (WorkCompleteSaved.OneShot == nil) then
  			-- load the defaults
--- 810,816 ----
  -- events for all addons loaded later).--
  -- this function works once when this addon loads
  	if arg1_name == "Work_Complete" then
! 		DEFAULT_CHAT_FRAME:AddMessage(myRed.."---["..myWhite.."Work_Complete"..myRed.."]---"..myYellow.." ver:"..myGreen..C_AddOns.GetAddOnMetadata("Work_Complete", "Version")..myWhite.." by "..myBlue.."PunksNotDead");
  		-- check if this is the first time the variables have been loaded
  		if (WorkCompleteSaved.OneShot == nil) then
  			-- load the defaults
***************
*** 901,907 ****
    WCpanel.name = "Work Complete";  --	This is the text that will display in the AddOn options list.
    -- Once a frame is ready to be used as a panel, it must be registered using the function
    -- InterfaceOptions_AddCategory, i.e. InterfaceOptions_AddCategory(panel)               
!   InterfaceOptions_AddCategory(WCpanel);
    --
    ---                                                                                                                                                 
  -- local VolumeText = WCpanel:CreateFontString("Work_Complete_Global_Text","ARTWORK","GameFontNormal");
--- 901,909 ----
    WCpanel.name = "Work Complete";  --	This is the text that will display in the AddOn options list.
    -- Once a frame is ready to be used as a panel, it must be registered using the function
    -- InterfaceOptions_AddCategory, i.e. InterfaceOptions_AddCategory(panel)               
!   --InterfaceOptions_AddCategory(WCpanel);
!   local category, layout = Settings.RegisterCanvasLayoutCategory(WCpanel, WCpanel.name);
!   Settings.RegisterAddOnCategory(category);
    --
    ---                                                                                                                                                 
  -- local VolumeText = WCpanel:CreateFontString("Work_Complete_Global_Text","ARTWORK","GameFontNormal");
***************
*** 919,925 ****
    ----inherits - Name of a template from which the new front string should inherit (string)
   local strWork_Complete_Version = WCpanel:CreateFontString("varWork_Complete_Global_Text","ARTWORK","GameFontNormalLarge");                                           
   strWork_Complete_Version:SetPoint("TOPLEFT", 20, -5);                                                                                                
!  strWork_Complete_Version:SetText("Work_Complete v:".. GetAddOnMetadata("Work_Complete", "Version"));  
   
   --   You can make a checkbox in WoW via the following commands:
   --     myCheckButton = CreateFrame("CheckButton", "myCheckButton_GlobalName", parentFrame, "ChatConfigCheckButtonTemplate")
--- 921,927 ----
    ----inherits - Name of a template from which the new front string should inherit (string)
   local strWork_Complete_Version = WCpanel:CreateFontString("varWork_Complete_Global_Text","ARTWORK","GameFontNormalLarge");                                           
   strWork_Complete_Version:SetPoint("TOPLEFT", 20, -5);                                                                                                
!  strWork_Complete_Version:SetText("Work_Complete v:".. C_AddOns.GetAddOnMetadata("Work_Complete", "Version"));  
   
   --   You can make a checkbox in WoW via the following commands:
   --     myCheckButton = CreateFrame("CheckButton", "myCheckButton_GlobalName", parentFrame, "ChatConfigCheckButtonTemplate")
***************
*** 1169,1172 ****
  	else
  		print("Work_Complete Debug is OFF", bolDebug);
  	end
! end
\ No newline at end of file
--- 1171,1174 ----
  	else
  		print("Work_Complete Debug is OFF", bolDebug);
  	end
! end

**Comment by halloaloe** [comment]
@tailcat
*** 1169,1172 ****
  	else
  		print("Work_Complete Debug is OFF", bolDebug);
  	end
! end
\ No newline at end of file
--- 1171,1174 ----
  	else
  		print("Work_Complete Debug is OFF", bolDebug);
  	end
! end
These two sections is where I lost the plot of your corrections. I don't see what's been changed. Please just list "On Line XXXX, change to: [insert line, corrections in bold]". My understanding of LUA is next to nothing, I really need to be guided here.

**Comment by tailcat** [comment]
> On Aug 18, 2024, at 9:42 PM, halloaloe ***@***.***> wrote:
> 
> 
> @tailcat
> *** 1169,1172 ****
> else
> print("Work_Complete Debug is OFF", bolDebug);
> end
> ! end
> \ No newline at end of file
> --- 1171,1174 ----
> else
> print("Work_Complete Debug is OFF", bolDebug);
> end
> ! end
> These two sections is where I lost the plot of your corrections. I don't see what's been changed. Please just list "On Line XXXX, change to: [insert line, corrections in bold]". My understanding of LUA is next to nothing, I really need to be guided here.
> 

Just ignore that that’s due to the missing newline

**Comment by stevedenunzio** [comment]
Message: ...dOns/SoulshapeJournal/Database/SoulshapeDatabase.lua:102: attempt to call global 'GetFactionInfoByID' (a nil value)
Time: Mon Aug 19 12:34:39 2024
Count: 1
Stack: ...dOns/SoulshapeJournal/Database/SoulshapeDatabase.lua:102: attempt to call global 'GetFactionInfoByID' (a nil value)
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals: parent = Frame {
 DragonflightLandingOverlay = Frame {
 }
}
overlayFrame = nil

**Comment by jalati** [comment]
@stevedenunzio You can change the following line from this:

`
name, _ = GetFactionInfoByID(faction.id)
`

to this:

`
        name, _ = C_Reputation.GetFactionInfoByID(faction.id)
`

The bulk of the changes can be found here in this PR:

https://github.com/christopheml/soulshape-journal/pull/72/files

**Comment by halloaloe** [comment]
I've made all suggested changes to SSJ listed here and the addon still doesn't work. Anything I'm missing?

**Comment by christopheml** [comment]
Fixes are on the way, thanks everyone for your patience and contributions.

**Comment by christopheml** [comment]
Version 1.2.5 is available here and on Curseforge.
