### ISSUE TITLE
Issues with "MountsJournal" and "Beast Squads" addons

### ISSUE THREAD

**Issue by LadyAtia** [christopheml/soulshape-journal#8]
Heyo :)

Currently your addon isn't working alongside thouse two. In the case of MountsJournal i can't see your soulshape page if I have it active, while Beast Squads tab is under your soulshape tap. I can give you screenshots if you need.

**Comment by LadyAtia** [comment]
Also, would it be possible to add filters for the normal and small soulshapes, aswell as an option to tag them (and the option to hide specific tags).

I love the idea of your addon so please keep working on it :)

**Comment by christopheml** [comment]
Hello, I'm on a trip abroad and will be investingating issues asap.
Thanks for the reporting.

AFAIK, addons use different ways of adding a new tab to the collection journal that may not be compatible, I'll see if I can find something that works properly.

**Comment by christopheml** [comment]
@LadyAtia Adding more filters, like soulshape/crittershape is already planned.

I'm going to investigate the interaction with MountsJournal, however I couldn't find an addon named "Beast Squads", it's probably a feature from another or pack, but I couldn't find it.

**Comment by penguinsane** [comment]
I believe this may be the addon they're referring to when they say "Beast Squad": https://www.curseforge.com/wow/addons/istablemaster

**Comment by christopheml** [comment]
Thank you, I'll look into it.

**Comment by christopheml** [comment]
OK, seems that iStableMaster implemented their own tab-handling logic, which unfortunately is not compatible with the way I chose (lib SecureTabs-2.0). There is no standard way of adding a new tab+panel to an existing default UI panel (here it's the Collections Journal), which means that addons using two different methods won't see each other's tabs and they will overlap.

The only possible fix here would be that iStableMaster uses lib SecureTabs-2.0 to handle their tabs, but I'm not exactly in a position to ask that from them 😅 

I'll document this known incompatibility in the readme and I'll close this.

**Comment by LadyAtia** [comment]
Hey :)

Have you also looked into the MountsJournal issue? I can still see it's
check mark in the soulshape journal which means I have to choose which one
I wanna see (if I have the mountsjournal checked in I see it twice
basically). Thanks for the update :)

Am So., 23. Jan. 2022 um 01:47 Uhr schrieb Christophe Michel <
***@***.***>:

**Comment by christopheml** [comment]
Hello, yes the bug with MountsJournal has been fixed, but that fix will be available in version 0.9. I still have a few things to do before I publish 0.9, the full list is [here](https://github.com/christopheml/soulshape-journal/milestone/2). I'll try to do this before the end of the week, hopefully tomorrow.

**Comment by christopheml** [comment]
@LadyAtia 0.9 is out on CurseForge, you should be able to use it with MountsJournal.
